sudo: false

language: node_js

node_js:
  - node

dist: trusty

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm install -g @angular/cli
  - npm install -g phonegap
  - npm install -g webpack

script:
  - ng test --browsers=ChromeHeadless --single-run --code-coverage
  - ng e2e

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: www
  on:
    branch: master
