sudo: false

language: node_js

node_js:
  - stable

dist: trusty

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm install -g codecov
  - npm install coveralls
  - npm install -g @angular/cli
  - npm install -g phonegap
  - npm install -g webpack

script:
  - ng test --single-run --code-coverage
  - ng e2e

after_success:
  - codecov
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: www
  on:
    branch: master
